"""
Grad-CAM style importance maps.

WARNING: Code below is generated by LLM.
    Usage has been shown to be satisfactory, however, it has not been manually
    verified to be correct by an expert.
"""

import numpy as np
import torch


def grad_cam(
    model,
    x,
    target_layer_name="bnorm_temporal",
    class_idx=None,
    reduce_to="electrodes",
    normalize=True,
):
    """
    Grad-CAM-style importance.

    Parameters
    ----------
    model : torch.nn.Module
        Trained Braindecode EEGNet.
    x : torch.Tensor
        Input EEG window. Expected shape: (1, n_chans, n_times).
    target_layer_name : str
        Layer to hook.
        Use "bnorm_temporal" for electrode importance.
        Use "conv_temporal" for electrode x time or time importance.
    class_idx : int | None
        Target class index. If None, uses predicted class.
    reduce_to : {"electrodes", "time", "electrode_time", "none"}
        How to reduce the Grad-CAM map.

        "electrodes"      -> shape (n_chans,)
        "time"            -> shape (n_times_after_layer,)
        "electrode_time"  -> shape (n_chans, n_times_after_layer)
        "none"            -> raw CAM shape after feature aggregation
    normalize : bool
        Whether to min-max normalize the output.

    Returns
    -------
    importance : np.ndarray
        Grad-CAM importance map.
    logits : torch.Tensor
        Model output logits on CPU.
    predicted_class : int
        Predicted class index.
    """

    model.eval()
    device = next(model.parameters()).device
    x = x.to(device).float()

    activations = {}
    gradients = {}

    modules = dict(model.named_modules())
    if target_layer_name not in modules:
        available = list(modules.keys())
        raise ValueError(
            f"Layer '{target_layer_name}' not found. "
            f"Available layers include: {available}"
        )

    target_layer = modules[target_layer_name]

    def forward_hook(module, inputs, output):
        activations["value"] = output

    def backward_hook(module, grad_input, grad_output):
        gradients["value"] = grad_output[0]

    forward_handle = target_layer.register_forward_hook(forward_hook)
    backward_handle = target_layer.register_full_backward_hook(backward_hook)

    try:
        model.zero_grad(set_to_none=True)

        logits = model(x)
        logits_flat = logits.reshape(logits.shape[0], -1)

        predicted_class = int(logits_flat.argmax(dim=1)[0])

        if class_idx is None:
            class_idx = predicted_class

        score = logits_flat[0, class_idx]
        score.backward()

        acts = activations["value"].detach()[0]
        grads = gradients["value"].detach()[0]

        # Grad-CAM:
        # average gradients over electrodes and time to get one weight per filter
        weights = grads.mean(dim=(1, 2), keepdim=True)

        # weighted sum across filters
        cam = torch.relu((weights * acts).sum(dim=0))
        # cam shape: (n_chans, n_times_after_layer)

        if reduce_to == "electrodes":
            importance = cam.mean(dim=-1)

        elif reduce_to == "time":
            importance = cam.mean(dim=0)

        elif reduce_to == "electrode_time":
            importance = cam

        elif reduce_to == "none":
            importance = cam

        else:
            raise ValueError(
                "reduce_to must be one of: "
                "'electrodes', 'time', 'electrode_time', or 'none'"
            )

        importance = importance.cpu().numpy()

        if normalize:
            min_val = importance.min()
            max_val = importance.max()
            importance = (importance - min_val) / (max_val - min_val + 1e-12)

        return importance, logits.detach().cpu(), predicted_class

    finally:
        forward_handle.remove()
        backward_handle.remove()
